name: dl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2019.3.9
  - cffi=1.12.2
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - dbus=1.13.6
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gettext=0.19.8.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.3
  - jpeg=9b
  - kiwisolver=1.0.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libpng=1.6.36
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4=2.2.1
  - lz4-c=1.8.3
  - matplotlib=3.0.3
  - mkl=2019.3
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - ninja=1.9.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - olefile=0.46
  - openssl=1.1.1b
  - pandas=0.24.2
  - pcre=8.43
  - pillow=5.4.1
  - pip=19.0.3
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.2.0
  - pytz=2018.9
  - qt=5.9.7
  - readline=7.0
  - scipy=1.2.1
  - setuptools=40.8.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.27.2
  - tk=8.6.8
  - torchvision=0.2.2
  - tornado=6.0.2
  - wheel=0.33.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7

